#! /bin/bash

pushd . > '/dev/null';
SCRIPT_PATH="${BASH_SOURCE[0]:-$0}";

while [ -h "$SCRIPT_PATH" ];
do
    cd "$( dirname -- "$SCRIPT_PATH"; )";
    SCRIPT_PATH="$( readlink -f -- "$SCRIPT_PATH"; )";
done


cd "$( dirname -- "$SCRIPT_PATH"; )" > '/dev/null';
SCRIPT_PATH="$( pwd; )/$1";
popd  > '/dev/null';

if [ -d "$SCRIPT_PATH" ]; then git diff --quiet HEAD^ HEAD "$SCRIPT_PATH"; else exit 0; fi;