/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AbstractSweetheartsInterface extends ethers.utils.Interface {
  functions: {
    "sweethearts(address)": FunctionFragment;
    "updateSweetheart(address,bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "sweethearts", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateSweetheart",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "sweethearts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSweetheart",
    data: BytesLike
  ): Result;

  events: {
    "SweetheartUpdated(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SweetheartUpdated"): EventFragment;
}

export type SweetheartUpdatedEvent = TypedEvent<
  [string, boolean] & { sweetheart: string; isSweeheart: boolean }
>;

export class AbstractSweethearts extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AbstractSweetheartsInterface;

  functions: {
    sweethearts(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    updateSweetheart(
      _sweetheart: string,
      _enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  sweethearts(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  updateSweetheart(
    _sweetheart: string,
    _enabled: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    sweethearts(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    updateSweetheart(
      _sweetheart: string,
      _enabled: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SweetheartUpdated(address,bool)"(
      sweetheart?: null,
      isSweeheart?: null
    ): TypedEventFilter<
      [string, boolean],
      { sweetheart: string; isSweeheart: boolean }
    >;

    SweetheartUpdated(
      sweetheart?: null,
      isSweeheart?: null
    ): TypedEventFilter<
      [string, boolean],
      { sweetheart: string; isSweeheart: boolean }
    >;
  };

  estimateGas: {
    sweethearts(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    updateSweetheart(
      _sweetheart: string,
      _enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    sweethearts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateSweetheart(
      _sweetheart: string,
      _enabled: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
