/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IKeeperIncentiveV2Interface extends ethers.utils.Interface {
  functions: {
    "burn(address)": FunctionFragment;
    "claim(bytes32[])": FunctionFragment;
    "createIncentive(address,uint256,bool,bool,address,uint256,uint256)": FunctionFragment;
    "fundIncentive(address,uint256,uint256)": FunctionFragment;
    "getAccounts(address)": FunctionFragment;
    "getControllerContracts()": FunctionFragment;
    "handleKeeperIncentive(bytes32,uint8,address)": FunctionFragment;
    "hasClaimableBalance(address)": FunctionFragment;
    "incentiveAccountId(address,uint256,address)": FunctionFragment;
    "tip(address,address,uint256,uint256)": FunctionFragment;
    "tipWithBurn(address,address,uint256,uint256,uint256)": FunctionFragment;
    "toggleApproval(address,uint8)": FunctionFragment;
    "toggleIncentive(address,uint8)": FunctionFragment;
    "updateBurnPercentage(uint256)": FunctionFragment;
    "updateIncentive(address,uint8,uint256,bool,bool,address,uint256,uint256)": FunctionFragment;
    "updateRequiredKeeperStake(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "burn", values: [string]): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike[]]): string;
  encodeFunctionData(
    functionFragment: "createIncentive",
    values: [
      string,
      BigNumberish,
      boolean,
      boolean,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fundIncentive",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAccounts", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getControllerContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleKeeperIncentive",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimableBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "incentiveAccountId",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tip",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tipWithBurn",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleApproval",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleIncentive",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBurnPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIncentive",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRequiredKeeperStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getControllerContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleKeeperIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incentiveAccountId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tipWithBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBurnPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRequiredKeeperStake",
    data: BytesLike
  ): Result;

  events: {};
}

export class IKeeperIncentiveV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IKeeperIncentiveV2Interface;

  functions: {
    burn(
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claim(
      incentiveAccountIds: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createIncentive(
      _address: string,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fundIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAccounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([BigNumber, string, string] & {
          balance: BigNumber;
          token: string;
          accountId: string;
        })[]
      ]
    >;

    getControllerContracts(overrides?: CallOverrides): Promise<[string[]]>;

    "handleKeeperIncentive(bytes32,uint8,address)"(
      arg0: BytesLike,
      _i: BigNumberish,
      _keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "handleKeeperIncentive(uint8,address)"(
      _i: BigNumberish,
      _keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasClaimableBalance(
      keeper: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    incentiveAccountId(
      _contractAddress: string,
      _i: BigNumberish,
      _rewardsToken: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    tip(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tipWithBurn(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleApproval(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateBurnPercentage(
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRequiredKeeperStake(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  burn(
    tokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claim(
    incentiveAccountIds: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createIncentive(
    _address: string,
    _reward: BigNumberish,
    _enabled: boolean,
    _openToEveryone: boolean,
    _rewardToken: string,
    _cooldown: BigNumberish,
    _burnPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fundIncentive(
    _contractAddress: string,
    _i: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAccounts(
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, string, string] & {
      balance: BigNumber;
      token: string;
      accountId: string;
    })[]
  >;

  getControllerContracts(overrides?: CallOverrides): Promise<string[]>;

  "handleKeeperIncentive(bytes32,uint8,address)"(
    arg0: BytesLike,
    _i: BigNumberish,
    _keeper: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "handleKeeperIncentive(uint8,address)"(
    _i: BigNumberish,
    _keeper: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasClaimableBalance(
    keeper: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  incentiveAccountId(
    _contractAddress: string,
    _i: BigNumberish,
    _rewardsToken: string,
    overrides?: CallOverrides
  ): Promise<string>;

  tip(
    _rewardToken: string,
    _keeper: string,
    _i: BigNumberish,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tipWithBurn(
    _rewardToken: string,
    _keeper: string,
    _i: BigNumberish,
    _amount: BigNumberish,
    _burnPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleApproval(
    _contractAddress: string,
    _i: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleIncentive(
    _contractAddress: string,
    _i: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateBurnPercentage(
    _burnPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateIncentive(
    _contractAddress: string,
    _i: BigNumberish,
    _reward: BigNumberish,
    _enabled: boolean,
    _openToEveryone: boolean,
    _rewardToken: string,
    _cooldown: BigNumberish,
    _burnPercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRequiredKeeperStake(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burn(tokenAddress: string, overrides?: CallOverrides): Promise<void>;

    claim(
      incentiveAccountIds: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    createIncentive(
      _address: string,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fundIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAccounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      ([BigNumber, string, string] & {
        balance: BigNumber;
        token: string;
        accountId: string;
      })[]
    >;

    getControllerContracts(overrides?: CallOverrides): Promise<string[]>;

    "handleKeeperIncentive(bytes32,uint8,address)"(
      arg0: BytesLike,
      _i: BigNumberish,
      _keeper: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "handleKeeperIncentive(uint8,address)"(
      _i: BigNumberish,
      _keeper: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasClaimableBalance(
      keeper: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    incentiveAccountId(
      _contractAddress: string,
      _i: BigNumberish,
      _rewardsToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    tip(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tipWithBurn(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleApproval(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBurnPercentage(
      _burnPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRequiredKeeperStake(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    burn(
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claim(
      incentiveAccountIds: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createIncentive(
      _address: string,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fundIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAccounts(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    getControllerContracts(overrides?: CallOverrides): Promise<BigNumber>;

    "handleKeeperIncentive(bytes32,uint8,address)"(
      arg0: BytesLike,
      _i: BigNumberish,
      _keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "handleKeeperIncentive(uint8,address)"(
      _i: BigNumberish,
      _keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasClaimableBalance(
      keeper: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incentiveAccountId(
      _contractAddress: string,
      _i: BigNumberish,
      _rewardsToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tip(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tipWithBurn(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleApproval(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateBurnPercentage(
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRequiredKeeperStake(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burn(
      tokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claim(
      incentiveAccountIds: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createIncentive(
      _address: string,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fundIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAccounts(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getControllerContracts(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "handleKeeperIncentive(bytes32,uint8,address)"(
      arg0: BytesLike,
      _i: BigNumberish,
      _keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "handleKeeperIncentive(uint8,address)"(
      _i: BigNumberish,
      _keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasClaimableBalance(
      keeper: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incentiveAccountId(
      _contractAddress: string,
      _i: BigNumberish,
      _rewardsToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tip(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tipWithBurn(
      _rewardToken: string,
      _keeper: string,
      _i: BigNumberish,
      _amount: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleApproval(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateBurnPercentage(
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateIncentive(
      _contractAddress: string,
      _i: BigNumberish,
      _reward: BigNumberish,
      _enabled: boolean,
      _openToEveryone: boolean,
      _rewardToken: string,
      _cooldown: BigNumberish,
      _burnPercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRequiredKeeperStake(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
