/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ParticipationRewardHelperInterface extends ethers.utils.Interface {
  functions: {
    "addShares(bytes32,address,uint256)": FunctionFragment;
    "contractName()": FunctionFragment;
    "initializeVault(bytes32,uint256)": FunctionFragment;
    "openVault(bytes32)": FunctionFragment;
    "participationReward()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addShares",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeVault",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openVault",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "participationReward",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participationReward",
    data: BytesLike
  ): Result;

  events: {};
}

export class ParticipationRewardHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ParticipationRewardHelperInterface;

  functions: {
    addShares(
      vaultId_: BytesLike,
      account_: string,
      shares_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contractName(overrides?: CallOverrides): Promise<[string]>;

    initializeVault(
      vaultId_: BytesLike,
      endTime_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openVault(
      vaultId_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    participationReward(overrides?: CallOverrides): Promise<[string]>;
  };

  addShares(
    vaultId_: BytesLike,
    account_: string,
    shares_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contractName(overrides?: CallOverrides): Promise<string>;

  initializeVault(
    vaultId_: BytesLike,
    endTime_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openVault(
    vaultId_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  participationReward(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addShares(
      vaultId_: BytesLike,
      account_: string,
      shares_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    contractName(overrides?: CallOverrides): Promise<string>;

    initializeVault(
      vaultId_: BytesLike,
      endTime_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    openVault(vaultId_: BytesLike, overrides?: CallOverrides): Promise<void>;

    participationReward(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addShares(
      vaultId_: BytesLike,
      account_: string,
      shares_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contractName(overrides?: CallOverrides): Promise<BigNumber>;

    initializeVault(
      vaultId_: BytesLike,
      endTime_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openVault(
      vaultId_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    participationReward(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addShares(
      vaultId_: BytesLike,
      account_: string,
      shares_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contractName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initializeVault(
      vaultId_: BytesLike,
      endTime_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openVault(
      vaultId_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    participationReward(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
