import Head from "next/head";
import Image from "next/image";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Dashboard from "@/components/Dashboard";
import asset_logo from "@/assets/logo.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>VCI - Creator Interface</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-slate-400/5 border-b border-slate-100 p-4">
        <nav className="w-full max-w-screen-lg mx-auto flex justify-end">
          <figure className="w-16">
            <Image src={asset_logo} alt="" />
          </figure>
          <div className="flex-grow" />
          <ConnectButton />
        </nav>
      </section>
      <main className="max-w-screen-lg mx-auto py-4">
        <Dashboard />
      </main>
    </>
  );
}
