/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { CrvAavePool, CrvAavePoolInterface } from "../CrvAavePool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[3]",
        name: "amounts",
        type: "uint256[3]",
      },
      {
        internalType: "uint256",
        name: "min_mint_amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "use_underlying",
        type: "bool",
      },
    ],
    name: "add_liquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CrvAavePool__factory {
  static readonly abi = _abi;
  static createInterface(): CrvAavePoolInterface {
    return new utils.Interface(_abi) as CrvAavePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CrvAavePool {
    return new Contract(address, _abi, signerOrProvider) as CrvAavePool;
  }
}
