/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { CurveRegistry, CurveRegistryInterface } from "../CurveRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "lp_token",
        type: "address",
      },
    ],
    name: "get_pool_from_lp_token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CurveRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): CurveRegistryInterface {
    return new utils.Interface(_abi) as CurveRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurveRegistry {
    return new Contract(address, _abi, signerOrProvider) as CurveRegistry;
  }
}
