/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CurveDepositZap,
  CurveDepositZapInterface,
} from "../CurveDepositZap";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256[4]",
        name: "amounts",
        type: "uint256[4]",
      },
      {
        internalType: "uint256",
        name: "min_mint_amounts",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "add_liquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CurveDepositZap__factory {
  static readonly abi = _abi;
  static createInterface(): CurveDepositZapInterface {
    return new utils.Interface(_abi) as CurveDepositZapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurveDepositZap {
    return new Contract(address, _abi, signerOrProvider) as CurveDepositZap;
  }
}
