/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRandomNumberConsumer,
  IRandomNumberConsumerInterface,
} from "../IRandomNumberConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "electionId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "seed",
        type: "uint256",
      },
    ],
    name: "getRandomNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "electionId",
        type: "uint256",
      },
    ],
    name: "getRandomResult",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRandomNumberConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomNumberConsumerInterface {
    return new utils.Interface(_abi) as IRandomNumberConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomNumberConsumer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRandomNumberConsumer;
  }
}
