/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  KeeperIncentivizedV1,
  KeeperIncentivizedV1Interface,
} from "../KeeperIncentivizedV1";

const _abi = [
  {
    inputs: [],
    name: "KEEPER_INCENTIVE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class KeeperIncentivizedV1__factory {
  static readonly abi = _abi;
  static createInterface(): KeeperIncentivizedV1Interface {
    return new utils.Interface(_abi) as KeeperIncentivizedV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KeeperIncentivizedV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as KeeperIncentivizedV1;
  }
}
