[profile.default]

src = 'contracts'
test = 'test'
out = 'artifacts'
libs = ['node_modules', '../../node_modules', "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  '@popcorn/hardhat/=./',
]

verbosity = 2
fuzz_runs = 256
fuzz_max_global_rejects = 100000000
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
FORKING_RPC_URL = "${FORKING_RPC_URL}"

[profile.ci]
src = 'contracts'
test = 'test'
out = 'artifacts'
libs = ['node_modules', '../../node_modules', "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  '@popcorn/hardhat/=./'
  
]
verbosity = 2
fuzz_max_global_rejects = 100000000
fuzz_runs = 2500
fs_permissions = [{ access = "read-write", path = "./"}]
